[package]
name = "lua_test"
version = "0.1.0"
edition = "2021"

[dependencies.mlua]
version = "0.9.7"
features = ["lua54", "async", "macros", "serialize", "vendored"]

[dependencies]
serde = "1.0.201"
serde_json = "1.0.117"